name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up dependencies (Linux)
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev rpm dpkg-dev
  
      - name: Set up dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install cmake nsis wixtoolset -y
  
      - name: Set up dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install cmake googletest
  
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
  
      - name: Create build directory
        run: cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install
  
      - name: Build
        run: cmake --build _build
